# Generated by Django 5.2.6 on 2025-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(verbose_name='updated_at')),
            ],
        ),
    ]
